export const buildStudentCredentialsMailTemplate = (collegeName, studentName, credentials) => {

  return `
<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f4f8ff;font-family:Segoe UI,Arial,sans-serif;">

<table width="100%" cellpadding="0" cellspacing="0">
  <tr>
    <td align="center" style="padding:40px 15px;">

      <table width="100%" style="max-width:560px;background:#ffffff;border-radius:14px;box-shadow:0 10px 40px rgba(37,99,235,0.18);overflow:hidden;">

        <!-- HEADER -->
        <tr>
          <td style="background:linear-gradient(135deg,#2563EB,#22D3EE);padding:26px 28px;color:#ffffff;">
            <h1 style="margin:0;font-size:22px;font-weight:600;">${collegeName}</h1>
            <p style="margin:6px 0 0;font-size:13px;opacity:0.9;">
              Powered by Smart Campus
            </p>
          </td>
        </tr>

        <!-- BODY -->
        <tr>
          <td style="padding:34px 30px;color:#0f172a;">

            <h2 style="margin:0 0 10px;font-size:21px;">Welcome to ${collegeName}</h2>

            <p style="margin:0 0 16px;line-height:1.6;color:#334155;">
              Dear <strong>${studentName}</strong>,
            </p>

            <p style="margin:0 0 20px;line-height:1.6;color:#334155;">
              Congratulations on your successful admission to  
              <strong>${collegeName}</strong>.  
              Below are your official student login credentials for accessing the Smart Campus portal:
            </p>

            <!-- CREDENTIAL CARD -->
            <div style="margin:18px 0;border-radius:12px;overflow:hidden;border:1px solid #bfdbfe;">
              <table width="100%" cellpadding="10" cellspacing="0" style="border-collapse:collapse;">
                <tr style="background:#2563EB;color:#ffffff;">
                  <th align="left">Login ID</th>
                  <th align="left">Password</th>
                </tr>
                <tr style="background:#ffffff;">
                  <td style="padding:10px;border-bottom:1px solid #e2e8f0;">${credentials.loginId}</td>
                  <td style="padding:10px;border-bottom:1px solid #e2e8f0;"><strong>${credentials.password}</strong></td>
                </tr>
              </table>
            </div>

            <div style="margin:18px 0;padding:14px 16px;background:#eff6ff;border-left:4px solid #2563EB;border-radius:6px;">
              ⚠️ <strong>Security Notice:</strong><br>
              This is a temporary password generated by the system.  
              Please change your password immediately after your first login to keep your account secure.
            </div>

            <p style="margin:22px 0 6px;color:#475569;">
              We wish you great success in your academic journey and are excited
              to support your learning experience through the Smart Campus platform.
            </p>

            <p style="margin:0;color:#475569;">
              Best wishes,<br>
              <strong>Smart Campus Support Team</strong>
            </p>

            <hr style="border:none;border-top:1px solid #e2e8f0;margin:26px 0;">

            <p style="font-size:13px;color:#64748b;line-height:1.6;">
              This is an automated message from Smart Campus.  
              Please do not reply to this email.
            </p>
          </td>
        </tr>

        <!-- FOOTER -->
        <tr>
          <td style="background:#f1f5ff;padding:14px 10px;text-align:center;font-size:12px;color:#64748b;">
            © 2025 Smart Campus Platform
          </td>
        </tr>

      </table>

    </td>
  </tr>
</table>

</body>
</html>
`;
};
